name: Build, Test, Deploy

on:
  workflow_dispatch:
    inputs:
      application-environment:
        type: choice
        description: What environment for the application to deploy to
        options:
          - dev
          - stage
          - prod
      run-unit-tests:
        type: boolean
      run-integration-tests:
        type: boolean
      run-end-to-end-tests:
        type: boolean
      # TODO: maybe have some sort of pre-built/cached application build to pull in the artifact and remove the build step altogether?

jobs:
    build:
        uses: ./.github/workflows/build.yaml

    test:
        needs: build
        uses: ./.github/workflows/test.yaml
        with:
          run-unit-tests: ${{ inputs.run-unit-tests }}
          run-integration-tests: ${{ inputs.run-integration-tests }}
          run-end-to-end-tests: ${{ inputs.run-end-to-end-tests }}

    deploy:
        needs: test
        uses: ./.github/workflows/deploy.yaml
        with:
          application-environment: ${{ inputs.application-environment }}

