name: Test
on:
    workflow_call:
        inputs:
            run-unit-tests:
                type: boolean
                description: Whether or not to run this type of test
            run-integration-tests:
                type: boolean
                description: Whether or not to run this type of test
            run-end-to-end-tests:
                type: boolean
                description: Whether or not to run this type of test 
    workflow_dispatch:
        inputs:
            run-unit-tests:
                type: boolean
                description: Whether or not to run this type of test
            run-integration-tests:
                type: boolean
                description: Whether or not to run this type of test
            run-end-to-end-tests:
                type: boolean
                description: Whether or not to run this type of test 

jobs:
    test:
        # TODO: make this dependent on the build
        runs-on: ubuntu-latest
        steps:
        - name: Unit tests
          if: ${{ inputs.run-unit-tests }}
          run: echo "Running unit tests"

        - name: Integration tests
          if: ${{ inputs.run-integration-tests }}
          run: echo "Running integration tests"

        - name: End to End tests
          if: ${{ inputs.run-end-to-end-tests }}
          run: echo "Running end to end tests"
